# Generated by Django 4.0.4 on 2022-05-24 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sede',
            old_name='Direccion',
            new_name='direccion',
        ),
        migrations.AddField(
            model_name='obrasocial',
            name='plan_obrasocial',
            field=models.CharField(default=datetime.date(2022, 5, 24), max_length=15),
            preserve_default=False,
        ),
    ]
