# Generated by Django 4.0.4 on 2022-07-23 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_turnos_turnodisponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turnos',
            name='usuario_turno',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariosturnos', to=settings.AUTH_USER_MODEL),
        ),
    ]
