# Generated by Django 4.0.4 on 2022-05-30 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_medicos_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='dni',
            field=models.IntegerField(default=22222222),
            preserve_default=False,
        ),
    ]
