# Generated by Django 4.0.4 on 2022-05-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_medicos_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_matricula',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nro_afiliado',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
