# Generated by Django 4.0.4 on 2024-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_num_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obrasocial',
            name='plan_obrasocial',
        ),
        migrations.AddField(
            model_name='user',
            name='num_matricula',
            field=models.IntegerField(null=True),
        ),
    ]
