# Generated by Django 4.0.4 on 2022-05-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_num_matricula_alter_user_nro_afiliado'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicos', to='api.medicos'),
        ),
    ]
