# Generated by Django 4.0.4 on 2024-02-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_obrasocial_plan_obrasocial_user_num_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='obrasocial',
            name='plan_obrasocial',
            field=models.CharField(default='Vacio', max_length=15),
            preserve_default=False,
        ),
    ]
